jobs:
  - template: build-and-test.yml
    parameters:
      vmImage: ubuntu-latest
      runtime: linux-x64
      name: Build_linux

  - template: build-and-test.yml
    parameters:
      vmImage: windows-latest
      runtime: win-x64
      name: Build_windows

  - template: build-and-test.yml
    parameters:
      vmImage: macOS-latest
      runtime: osx-x64
      name: Build_macOS
