jobs:
- template: build-and-test.yml
  parameters:
    vmImage: ubuntu-16.04
    runtime: linux-x64
    name: Build_linux

- template: build-and-test.yml
  parameters:
    vmImage: windows-2019
    runtime: win-x64
    name: Build_windows

- template: build-and-test.yml
  parameters:
    vmImage: macOS-10.14
    runtime: osx-x64
    name: Build_macOS